name: Discuss Bot

on:
  discussion:
    types:
      - created

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run discuss bot
        run: python main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
